### ISSUE TITLE
Paper links 

### ISSUE THREAD

**Issue by harshakokel** [prl-theworkshop/prl-theworkshop.github.io#1]
Hello,

The links near the accepted paper on the website do not refer to correct pdfs.

Regards,
Harsha Kokel.

**Comment by hectorpal** [comment]
Hi Harsha,

Thank you for letting us know.
I fixed it a 1/2 hour ago.
This one should be working: https://github.com/prl-theworkshop/prl-theworkshop.github.io
https://prl-theworkshop.github.io/ might need to be reloaded. 

Please let me know if it's still not working.

Best,
Hector
